server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location /clients-api/ {
        proxy_pass http://owclients:8080;
        proxy_set_header Authorization $http_authorization;
        proxy_read_timeout 120s;
        proxy_buffering off;
        access_log off;
    }
    location / { try_files $uri $uri/ /index.html; }
}
