const assert = require('node:assert/strict');
const fs = require('node:fs');
const routes = fs.readFileSync('src/router/routes.tsx', 'utf8');
const clients = routes.slice(routes.indexOf("id: 'clients'"), routes.indexOf("id: 'scripts'"));
assert.ok(routes.indexOf("id: 'clients'") > routes.indexOf("id: 'firmware-group'"));
assert.match(clients, /name: 'Clients'/);
assert.match(clients, /authorized: \['root'\]/);
assert.match(clients, /<Laptop size=\{28\} weight="bold"/);
const page = fs.readFileSync('src/pages/Clients/index.tsx', 'utf8');
assert.match(page, /Show historic clients/);
assert.match(page, /useState\(false\)/);
assert.match(page, /enabled: root && !!token/);
assert.match(page, /<DataGrid<Association>/);
assert.match(page, /showAsCard: true/);
assert.ok(page.indexOf("id: 'vendor'") > page.indexOf("id: 'mac'") && page.indexOf("id: 'vendor'") < page.indexOf("id: 'ip'"));
const vm = require('node:vm');
const context = {};
vm.createContext(context);
vm.runInContext(fs.readFileSync('src/pages/Clients/vendors.js', 'utf8').replace(/export /g, '') + '\nthis.vendorFor = vendorFor; this.vendorColumnOrder = vendorColumnOrder;', context);
assert.equal(context.vendorFor('18:B4:30:13:AF:E9', { '18b43013afe9': 'Example vendor' }), 'Example vendor');
assert.equal(context.vendorFor('02:11:22:33:44:55', { '021122334455': 'Do not guess' }), 'Private MAC');
assert.equal(context.vendorFor('00:11:22:33:44:55', {}), 'Unknown');
assert.deepEqual(Array.from(context.vendorColumnOrder(['mac', 'ip', 'ssid'])), ['mac', 'vendor', 'ip', 'ssid']);
assert.deepEqual(Array.from(context.vendorColumnOrder(['vendor', 'mac', 'ip'])), ['vendor', 'mac', 'ip']);
console.log('PASS: Clients menu placement, label, icon, root gate and historic default');
vm.runInContext(fs.readFileSync('src/pages/Clients/freshness.js', 'utf8').replace(/export /g, '') + '\nthis.clientStatus = clientStatus; this.latestClients = latestClients; this.statusColumnOrder = statusColumnOrder;', context);
const recent = { mac: 'aa:bb:cc:dd:ee:ff', lastSeen: 990, endTime: null, apConnected: true, apSerial: 'new' };
assert.equal(context.clientStatus(recent, 1000).label, 'Recent');
assert.equal(context.clientStatus(recent, 1600).label, 'Stale');
assert.equal(context.clientStatus({ ...recent, apConnected: false }, 1000).label, 'Stale');
assert.equal(context.clientStatus(recent, 1000, true).label, 'Stale');
assert.equal(context.clientStatus({ ...recent, lastSeen: NaN }, 1000).label, 'Unknown');
assert.equal(context.clientStatus({ ...recent, lastSeen: 0 }, 1000).label, 'Unknown');
assert.equal(context.clientStatus({ ...recent, lastSeen: 2000 }, 1000).label, 'Unknown');
assert.equal(context.clientStatus({ ...recent, endTime: 995 }, 1000, true).label, 'Historic');
const old = { ...recent, mac: 'AABBCCDDEEFF', lastSeen: 900, apSerial: 'old' };
assert.equal(context.latestClients([old, recent], false).length, 1);
assert.equal(context.latestClients([recent, old], false)[0].apSerial, 'new');
assert.equal(context.latestClients([old, recent], true).length, 2);
assert.equal(context.latestClients([{ ...old, endTime: 999 }, recent], false).length, 1);
assert.equal(context.latestClients([{ ...old, lastSeen: 990, apConnected: false }, recent], false)[0].apSerial, 'new');
assert.deepEqual(Array.from(context.statusColumnOrder(['mac', 'vendor', 'ip'])), ['mac', 'vendor', 'status', 'ip']);
assert.match(page, /setInterval.*30000/);
assert.match(page, /clientStatus\(row, now, query.isError\)/);
console.log('PASS: client freshness, offline/error/invalid timestamps, roaming deduplication and historic retention');
